import localFont from "next/font/local";
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
import { DM_Sans, Playfair_Display } from 'next/font/google';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Specify the font weights you want to include.
  style: ['normal'], // Optionally, specify styles like normal or italic.
  display: 'swap', // This ensures text is displayed using fallback fonts until the custom font loads.
})
const dmSans = DM_Sans({
  subsets: ['latin'], // You can specify 'latin' or other subsets depending on the characters you need.
  weight: ['400', '500', '700'], // Specify the font weights you want to include.
  style: ['normal', 'italic'], // Optionally, specify styles like normal or italic.
  display: 'swap', // This ensures text is displayed using fallback fonts until the custom font loads.
});

export const metadata = {
  title: "Bistro Bliss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.className} ${playfairDisplay.className}  antialiased overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
